// NOTE: targets the removed wallet-login flow (cookie sessions). Google sign-in plus a linked wallet replaced it; needs a rewrite before use.
// Optional local Chrome regression: start mock backend on8788 with WEB_ORIGINS=http://localhost:3002
// and TOPUP_COOLDOWN_SECONDS=0; build/start web on3002 with NEXT_PUBLIC_BACKEND_URL=http://localhost:8788.
// Set PLAYWRIGHT_MODULE to an installed Playwright module path, or install Playwright in your test environment.
// Uses a fresh test-only wallet, no external provider or real blockchain transactions.
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE ?? 'playwright');
import { createRequire } from 'node:module';
import { createPrivateKey, sign } from 'node:crypto';
import assert from 'node:assert/strict';
const require = createRequire(new URL('../../backend/package.json', import.meta.url));
const { Keypair } = require('@solana/web3.js');
const key = Keypair.generate(), address = key.publicKey.toBase58();
const signing = createPrivateKey({key:Buffer.concat([Buffer.from('302e020100300506032b657004220420','hex'),Buffer.from(key.secretKey.slice(0,32))]),format:'der',type:'pkcs8'});
const browser = await chromium.launch({channel:'chrome',headless:true});
try {
const context = await browser.newContext(); const page = await context.newPage();
const errors=[]; page.on('pageerror', e=>errors.push(e.message));
const privateRequests=[]; page.on('request', r=>{if (/localhost:8788\/(pouches|orders|stats|chat)/.test(r.url())) privateRequests.push(r.url());});
await page.goto('http://localhost:3002/dashboard');
await page.getByRole('button',{name:'Connect and sign in',exact:true}).waitFor();
assert.equal(privateRequests.length,0,'No private data requests before sign-in');
await page.getByRole('button',{name:'Connect and sign in',exact:true}).click();
await page.getByRole('alert').filter({hasText:'Phantom or Solflare'}).waitFor();
await page.exposeFunction('testSign', bytes => [...sign(null,Buffer.from(bytes),signing)]);
await page.evaluate(address=>{window.solana={publicKey:{toBase58:()=>address},connect:async()=>({publicKey:{toBase58:()=>address}}),signMessage:async(message)=>({signature:new Uint8Array(await window.testSign([...message]))})};},address);
await page.getByRole('button',{name:'Connect and sign in',exact:true}).click();
await page.getByRole('button',{name:'Sign out',exact:true}).waitFor();
const stored=await page.evaluate(()=>localStorage.getItem('solpouch.session')); assert(stored,'Session is kept in localStorage under solpouch.session');
const p = await page.evaluate(async()=>{ const r=await fetch('http://localhost:8788/pouches',{method:'POST',credentials:'include',headers:{'content-type':'application/json'},body:JSON.stringify({name:'Browser test pouch',maxPerOrder:10000000,dailyLimit:20000000,allowedMerchantIds:['mountain-market']})});return {status:r.status,body:await r.json()}; });
assert.equal(p.status,201,JSON.stringify(p));
await page.goto(`http://localhost:3002/pouches/${p.body.id}`);
await page.getByRole('heading',{name:'Browser test pouch',exact:true}).waitFor();
await page.getByLabel('Amount · USDC',{exact:true}).fill('20');
await page.getByLabel('What is this refill for?',{exact:true}).fill('Browser recovery test');
await page.getByRole('button',{name:'Start top-up',exact:true}).click();
await page.getByRole('button',{name:'Complete top-up',exact:true}).waitFor();
const savedBefore=await page.evaluate(()=>Object.entries(localStorage).filter(([k])=>k.startsWith('solpouch:topup:')));
assert.equal(savedBefore.length,1);
await page.reload();
await page.getByRole('button',{name:'Complete top-up',exact:true}).waitFor();
const savedAfter=await page.evaluate(()=>Object.entries(localStorage).filter(([k])=>k.startsWith('solpouch:topup:')));
assert.deepEqual(savedAfter,savedBefore);
await page.route('**/topups/*/complete',async route=>{await route.fetch();await route.abort('failed');},{times:1});
await page.getByRole('button',{name:'Complete top-up',exact:true}).click();
await page.getByRole('button',{name:'Check top-up status',exact:true}).waitFor();
await page.reload();
await page.getByText('Top-up complete. Your balance has been updated.',{exact:true}).waitFor();
const balance=await page.evaluate(async id=>(await (await fetch(`http://localhost:8788/pouches/${id}`,{credentials:'include'})).json()).balance,p.body.id);
assert.equal(balance,20000000,'Lost response/reload must credit once');
console.log('AUTH_TOPUP_RELOAD_AND_LOST_RESPONSE_OK');
await page.screenshot({path:'/tmp/solpouch-backend-authenticated.png',fullPage:true});
await page.getByRole('button',{name:'Ask Solpouch',exact:true}).click();
await page.getByText('Voice unavailable. The text helper is available.',{exact:true}).waitFor();
await page.getByRole('textbox',{name:'Message Solpouch',exact:true}).fill('What is my balance?');
await page.getByRole('button',{name:'Send',exact:true}).click();
await page.getByRole('log',{name:'Conversation'}).getByText('Solpouch',{exact:true}).waitFor();
await page.getByRole('button',{name:'Close chat',exact:true}).click();
await page.route('**/auth/voice-status',r=>r.fulfill({status:200,contentType:'application/json',body:JSON.stringify({enabled:true})}));
let releaseSession; const heldSession=new Promise(r=>releaseSession=r); let sessionRequested=false;
await page.route('**/auth/voice-session',async r=>{sessionRequested=true;await heldSession;await r.fulfill({status:503,contentType:'application/json',body:JSON.stringify({error:'fixture connection failure'})});});
await page.getByRole('button',{name:'Ask Solpouch',exact:true}).click();
await page.getByText('Agent sessions last five minutes.',{exact:true}).waitFor();
await page.getByRole('button',{name:'Clear chat',exact:true}).click();
let fallbackRequests=0; page.on('request',r=>{if(r.url()==='http://localhost:8788/chat'&&r.method()==='POST')fallbackRequests++;});
await page.getByRole('textbox',{name:'Message Solpouch',exact:true}).fill('What is my balance?');
await page.getByRole('button',{name:'Send',exact:true}).click();
await page.getByRole('button',{name:'Cancel connection',exact:true}).waitFor();
await page.getByRole('button',{name:'Cancel connection',exact:true}).click();
releaseSession();
await page.getByRole('button',{name:'Talk',exact:true}).waitFor();
await page.waitForTimeout(350);
assert.equal(fallbackRequests,0,'Cancelling connection must not send fallback message');
await page.getByRole('textbox',{name:'Message Solpouch',exact:true}).fill('Explain spending limits');
await page.getByRole('button',{name:'Send',exact:true}).click();
await page.getByText('The agent could not connect. Using the read-only text helper.',{exact:true}).waitFor();
await page.getByRole('log',{name:'Conversation'}).getByText('Solpouch',{exact:true}).waitFor();
assert.equal(fallbackRequests,1);
console.log('CHAT_FALLBACK_AND_CANCEL_OK');
await page.getByRole('button',{name:'Sign out',exact:true}).click();
await page.getByRole('button',{name:'Connect and sign in',exact:true}).waitFor();
assert(!await page.getByRole('heading',{name:'Browser test pouch',exact:true}).count());
assert.equal(errors.length,0,errors.join('\n'));
console.log('LOGOUT_OK');
} finally {await browser.close();}
